[project]
name = "task-cli"
version = "1.0.0"
description = "Простой CLI-трекер задач"
authors = [{ name = "Влад" }]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "typer>=0.12.3"
]

[project.scripts]
task-cli = "task_cli.main:app"
